### ISSUE TITLE
[Single Interpretation] [Antibiotic Code] - Throws if invalid format of antibiotic code is passed in or user input 

### ISSUE THREAD

**Issue by ibrahimhuycn** [AClark-WHONET/AMRIE#8]
# Scenario
On the tab page `Single Interpretation`, if the user enters antibiotic code without following the "WHONET antibiotic column naming conventions" with the rest of the details entered correctly then the software throws an exception as below.

```
************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key 'ND10' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AMR_Engine.IsolateInterpretation.GetSingleInterpretation(String antibioticFullCode) in C:\Users\Ibrahim\Source\Repos\SwatInc\AMRIE\Interpretation Engine\IsolateInterpretation.cs:line 165
   at AMR_Engine.IsolateInterpretation.GetSingleInterpretation(InterpretationConfiguration interpretationConfig, String organismCode, String antibioticCode, String measurement) in C:\Users\Ibrahim\Source\Repos\SwatInc\AMRIE\Interpretation Engine\IsolateInterpretation.cs:line 139
   at AMR_InterpretationInterface.MainApplicationForm.GetInerpretationsButton_Click(Object sender, EventArgs e) in C:\Users\Ibrahim\Source\Repos\SwatInc\AMRIE\Interpretation Interface\MainApplicationForm.cs:line 166
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

``` 

# Probable cause
The antibiotic code is not added to the `Dictionary` variable named `ApplicableAntibioticSpecificRules` if the antibiotic code fails validation as per the regex. The relevent part of the code is below.
```csharp
// FILE NAME: IsolateInterpretation.cs
// LINE NUMBER: 59
public IsolateInterpretation(Dictionary<string, string> dataRowValues_, List<string> columnNames_,  List<string> enabledExpertInterpretationRules_,
	List<Breakpoint> userDefinedBreakpoints,
	int guidelineYear = -1, List<string> prioritizedBreakpointTypes = null, List<string> prioritizedSitesOfInfection = null)
{
	// removed the code here for simplicity

	AntibioticFields = DataRowValues.Keys.Where(k => ValidAntibioticFieldNameRegex.IsMatch(k)); // THIS RETURNS ONLY VALID ANTIBIOTIC CODES
	foreach (string fieldName in AntibioticFields)
	{
		//removed the code here for simplicity
		
		ApplicableAntibioticSpecificRules.Add(fieldName, thisAbxSpecificRuleSet); // SO WILL NOT BE ADDED HERE IF THE ANTIBIOTIC CODE IS INVALID
	}
	
	//removed the code here for simplicity
}
```

In case the entered antibiotic code is invalid, it is not added to `ApplicableAntibioticSpecificRules` but the interpretation step tries to access the invalid antibiotic code which does not exist by key as shown below. This throws uncaught exception.
```csharp
// FILE NAME: IsolateInterpretation.cs
// LINE NUMBER: 162
private string GetSingleInterpretation(string antibioticFullCode)
{
  if (!ResultInterpretations.ContainsKey(antibioticFullCode))
    ResultInterpretations.Add(antibioticFullCode,
      ApplicableAntibioticSpecificRules[antibioticFullCode].GetInterpretation());

  /*
	 * 1. The variable antibioticFullCode is not validated so it can be anything
	 * 2. The key will be present in `ApplicableAntibioticSpecificRules` only if the antibioticFullCode is valid. 
	 * 3. This means if the antibiotic code is not valid, trying to accesss by the key throws an error as shown above
	 */

  return ResultInterpretations[antibioticFullCode];
}
```
I suggest to show a helpful message which explains the format of antibiotic codes or to point to where the user can lookup the antibiotic code they need. I thought of submitting a pull request but did not since I dont know how you will want to fix the issue.

**Comment by AClark-WHONET** [comment]
Hi @ibrahimhuycn,

Thanks for reporting this issue. I will update the interface to include a list of antibiotics and some other relevant controls which prevent invalid entries by design, and don't require the user to be familiar with the codes.

**Comment by AClark-WHONET** [comment]
Hello @ibrahimhuycn,

I've finished with the updates I planned to make to the "single interpretation" screen. If you would like, you can check out the branch associated with this issue to provide feedback before I merge this work.

Thanks!
